In [29]:
import kaggle
from sklearn.preprocessing import OrdinalEncoder, StandardScaler, LabelEncoder
from sklearn.feature_selection import mutual_info_classif
import pandas as pd
import numpy as np

In [20]:
df = pd.read_csv('./dataset/UCI_Credit_Card.csv')
df.dropna(inplace=True)
df.head(5)

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [21]:
df['SEX'] = np.where(df['SEX'] == 1, 0, 1)

In [22]:
df['MARRIAGE'].unique()

array([1, 2, 3, 0])

In [23]:
# drow rows where Education is 0, 4,5, or 6
df = df[~df['EDUCATION'].isin([0, 4, 5, 6])]
#  drop rows where Mariage is 0
df = df[~df['MARRIAGE'].isin([0])]
# drop roes where PAY_0,2,3,4,5,6 is -2
df = df[~df['PAY_0'].isin([-2])]
df = df[~df['PAY_2'].isin([-2])]
df = df[~df['PAY_3'].isin([-2])]
df = df[~df['PAY_4'].isin([-2])]
df = df[~df['PAY_5'].isin([-2])]
df = df[~df['PAY_6'].isin([-2])]
# change valuse in pay from -1 to 0
df['PAY_0'] = np.where(df['PAY_0'] == -1, 0, df['PAY_0'])
df['PAY_2'] = np.where(df['PAY_2'] == -1, 0, df['PAY_2'])
df['PAY_3'] = np.where(df['PAY_3'] == -1, 0, df['PAY_3'])
df['PAY_4'] = np.where(df['PAY_4'] == -1, 0, df['PAY_4'])
df['PAY_5'] = np.where(df['PAY_5'] == -1, 0, df['PAY_5'])
df['PAY_6'] = np.where(df['PAY_6'] == -1, 0, df['PAY_6'])
# shift and reverse valus of MARRIAGE down by 1
df['MARRIAGE'] = np.where(df['MARRIAGE'] == 1, 0, 1)
# shift Education values down by 1
df['EDUCATION'] = df['EDUCATION'] - 1

In [26]:
# drop ID column
df.drop(columns=['ID'], inplace=True)

In [24]:
df['EDUCATION'].unique()

array([1, 0, 2])

In [27]:
df.head(5)

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
1,120000.0,1,1,1,26,0,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,1,1,1,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,1,1,0,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,0,1,0,57,0,0,0,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
5,50000.0,0,0,1,37,0,0,0,0,0,...,19394.0,19619.0,20024.0,2500.0,1815.0,657.0,1000.0,1000.0,800.0,0

In [ ]:
# Classification Mutual Information
discrete_features = [False] * 23
for col in [1,2,3,5,6,7,8,9,10]:
    discrete_features[col] = True
X = df.drop(columns=['default.payment.next.month'])
y = df['default.payment.next.month']
mi = mutual_info_classif(X, y, discrete_features=discrete_features)
mi_scores = pd.Series(mi, index=X.columns).sort_values(ascending=False)
print(mi_scores)

PAY_0        0.090446
PAY_2        0.059341
PAY_3        0.045437
PAY_4        0.040190
PAY_5        0.037342
PAY_6        0.032814
PAY_AMT1     0.030635
PAY_AMT3     0.022520
PAY_AMT2     0.021662
PAY_AMT4     0.021405
PAY_AMT5     0.019633
PAY_AMT6     0.017055
LIMIT_BAL    0.015358
BILL_AMT3    0.008929
BILL_AMT1    0.008922
BILL_AMT5    0.006669
BILL_AMT2    0.005225
BILL_AMT4    0.004350
AGE          0.003053
BILL_AMT6    0.002527
EDUCATION    0.001924
SEX          0.000751
MARRIAGE     0.000573
dtype: float64

In [31]:
df.head(2)

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
1,120000.0,1,1,1,26,0,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,1,1,1,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0

In [34]:
# Regression Mutual Information
from sklearn.feature_selection import mutual_info_regression
X = df.drop(columns=['LIMIT_BAL'])
y = df['LIMIT_BAL']
discrete_features = [False] * 23
for col in [1,2,3,5,6,7,8,9,10,23]:
    discrete_features[col-1] = True

mi_scores = mutual_info_regression(X, y, discrete_features=discrete_features)
mi_df = (
    pd.Series(mi_scores, index=X.columns)
    .sort_values(ascending=False)
)

print("Mutual Information scores:")
print(mi_df)

Mutual Information scores:
BILL_AMT1                     0.565272
BILL_AMT2                     0.548127
BILL_AMT3                     0.513471
BILL_AMT4                     0.460832
BILL_AMT5                     0.448818
BILL_AMT6                     0.444930
PAY_AMT1                      0.244176
PAY_AMT2                      0.232635
PAY_AMT4                      0.225951
PAY_AMT5                      0.222194
PAY_AMT6                      0.222051
PAY_AMT3                      0.221064
AGE                           0.076830
EDUCATION                     0.035104
PAY_0                         0.031714
PAY_2                         0.030165
PAY_4                         0.027069
PAY_3                         0.026571
PAY_6                         0.023621
PAY_5                         0.021245
default.payment.next.month    0.015480
SEX                           0.013970
MARRIAGE                      0.008594
dtype: float64